name: Build workflow
on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build ipa
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          bundle install -j 4
          bundle exec fastlane build_unsign_ipa

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Store artifact's name
        id: artifact-name
        run: echo "{name}=${GITHUB_REF##*/}-nosign.ipa" >> $GITHUB_OUTPUT

      - name: List, filter and delete artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const { owner, repo } = context.issue
            
            const res = await github.rest.actions.listArtifactsForRepo({
              owner,
              repo,
            })
            
            res.data.artifacts
              .filter(({ name }) => name === '${{ steps.artifact-name.outputs.value }}')
              .forEach(({ id }) => { github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id, }) })

      - name: Upload latest artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifact-name.outputs.value }}
          path: BilbiliAtvDemo.ipa
          retention-days: 30